# Generated by Django 3.0.8 on 2020-08-02 23:46

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('badge_name', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('pronouns', models.CharField(max_length=32)),
                ('shirt_size', models.CharField(choices=[('XS', 'extra small'), ('SM', 'small'), ('MD', 'medium'), ('L', 'large'), ('XL', 'extra large'), ('XXL', 'extra extra large')], max_length=3)),
                ('birth_date', models.DateField()),
                ('agrees_to_con_tos', models.BooleanField()),
                ('delete_info', models.BooleanField()),
                ('address1', models.CharField(max_length=1024, verbose_name='Address line 1')),
                ('address2', models.CharField(max_length=1024, verbose_name='Address line 2')),
                ('zip_code', models.CharField(max_length=12, verbose_name='ZIP / Postal code')),
                ('city', models.CharField(max_length=1024, verbose_name='City')),
                ('state', models.CharField(max_length=64, verbose_name='State')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('phone_number', models.CharField(default='XXXXXXXXXX', max_length=12)),
                ('agrees_to_surveys', models.BooleanField()),
                ('request_volunteer_info', models.BooleanField()),
                ('request_asl', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Banned',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('badge_name', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('pronouns', models.CharField(max_length=32)),
                ('shirt_size', models.CharField(choices=[('XS', 'extra small'), ('SM', 'small'), ('MD', 'medium'), ('L', 'large'), ('XL', 'extra large'), ('XXL', 'extra extra large')], max_length=3)),
                ('birth_date', models.DateField()),
                ('agrees_to_con_tos', models.BooleanField()),
                ('delete_info', models.BooleanField()),
                ('reason', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Charity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(blank=True, help_text='Charity link', max_length=500, verbose_name='URL')),
                ('donations', models.DecimalField(decimal_places=2, default=0, help_text='External donations to add to metrics', max_digits=12)),
            ],
            options={
                'verbose_name_plural': 'Charities',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_name', models.CharField(max_length=100)),
                ('percent_off', models.IntegerField(null=True)),
                ('amount_off', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('single_use', models.BooleanField(default=False)),
                ('used', models.IntegerField(default=0)),
                ('reason', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Merchandise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('category', models.CharField(choices=[('S', 'Shirt'), ('A', 'Accessory'), ('B', 'Book'), ('MISC', 'Misc.')], max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('badge_name', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('pronouns', models.CharField(max_length=32)),
                ('shirt_size', models.CharField(choices=[('XS', 'extra small'), ('SM', 'small'), ('MD', 'medium'), ('L', 'large'), ('XL', 'extra large'), ('XXL', 'extra extra large')], max_length=3)),
                ('birth_date', models.DateField()),
                ('agrees_to_con_tos', models.BooleanField()),
                ('delete_info', models.BooleanField()),
                ('venue', models.CharField(max_length=64)),
                ('business_name', models.CharField(max_length=64)),
                ('business_license', models.FileField(upload_to='uploads/merchant/licenses/%Y/%m/%d/')),
                ('website', models.URLField()),
                ('agrees_to_merchant_tos', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('badge_name', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('pronouns', models.CharField(max_length=32)),
                ('shirt_size', models.CharField(choices=[('XS', 'extra small'), ('SM', 'small'), ('MD', 'medium'), ('L', 'large'), ('XL', 'extra large'), ('XXL', 'extra extra large')], max_length=3)),
                ('birth_date', models.DateField()),
                ('agrees_to_con_tos', models.BooleanField()),
                ('delete_info', models.BooleanField()),
                ('needs_room', models.BooleanField()),
                ('special_skills', models.TextField(blank=True)),
                ('checked_in', models.BooleanField()),
                ('diet_restrictions', models.TextField(blank=True)),
                ('department_head', models.BooleanField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regcore_api.Department')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regcore_api.Staff')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PriceLevelOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('option_image', models.ImageField(blank=True, null=True, upload_to='price_level/%Y/%m/%d')),
                ('active', models.BooleanField(default=False)),
                ('rank', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('public', models.BooleanField()),
                ('merch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regcore_api.Merchandise')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dealer_reg_star', models.DateTimeField(help_text='Start date and time for dealer applications', verbose_name='Dealer Registration Start')),
                ('dealer_reg_end', models.DateTimeField(verbose_name='Dealer Registration End')),
                ('staff_reg_start', models.DateTimeField(help_text='(Not currently enforced)', verbose_name='Staff Registration Start')),
                ('staff_reg_end', models.DateTimeField(verbose_name='Staff Registration End')),
                ('attendee_reg_start', models.DateTimeField(verbose_name='Attendee Registration Start')),
                ('attendee_reg_end', models.DateTimeField(verbose_name='Attendee Registration End')),
                ('onsite_reg_start', models.DateTimeField(help_text='Start time for /registration/onsite form', verbose_name='On-site Registration Start')),
                ('onsite_reg_end', models.DateTimeField(verbose_name='On-site Registration End')),
                ('event_start', models.DateField(verbose_name='Event Start Date')),
                ('event_end', models.DateField(verbose_name='Event End Date')),
                ('registration_email', models.CharField(blank=True, help_text='Email to display on error messages for attendee registration', max_length=200, verbose_name='Registration Email')),
                ('staff_email', models.CharField(blank=True, help_text='Email to display on error messages for staff registration', max_length=200, verbose_name='Staff Email')),
                ('dealer_email', models.CharField(blank=True, help_text='Email to display on error messages for dealer registration', max_length=200, verbose_name='Dealer Email')),
                ('code_of_conduct', models.FileField(blank=True, null=True, upload_to='codes_of_conduct/%Y/%m/%d')),
                ('charity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='regcore_api.Charity')),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('relation', models.CharField(max_length=32)),
                ('phone_number', models.CharField(default='XXXXXXXXXX', max_length=12)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
    ]
