# Generated by Django 3.0.8 on 2020-10-17 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regcore_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='phone_number',
            field=models.CharField(default='XXXXXXXXXX', max_length=15),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='phone_number',
            field=models.CharField(default='XXXXXXXXXX', max_length=15),
        ),
    ]
